### ISSUE TITLE
nerf skybases

### ISSUE THREAD

**Issue by SonantDread** [Gingerbeard5773/Zombies_Reborn#156]
people sit in towers constantly instead of contributing to gameplay, i think this can be easily remidied with a shorter height or a way for zombies to better break them down

**Comment by Ctaehko** [comment]
+1 on this, dark wraiths should spawn from the sky and target the tallest playermade building, or the build height should be halved, it's just a way of griefing with the amount of resources they steal from people trying to build defences

**Comment by Gingerbeard5773** [comment]
I am not sure what should be done, or if anything should be done at all. consider the following;

Sky bases are usually a losing strategy due to the lack of resources and space. Without trees or grain, sky bases are strangled by a lack of economy. This is somewhat remedied by a reliable trader spawn though, but without any decent income from killing zombies its basically useless.

The introduction of the dark wraith also makes sky bases even less optimal, though with enough migrant bow spam this is not a concern.
