### ISSUE TITLE
iron arrows

### ISSUE THREAD

**Issue by karasik112** [Gingerbeard5773/Zombies_Reborn#168]
default arrows but higher damage and requires iron ingots to make

**Comment by RobotDerevo** [comment]
████████████████████████████████████████████████
█▄─▄█▄─▀█▀─▄█▄─▄▄─█─▄▄─█─▄▄▄▄█─▄─▄─█▄─▄▄─█▄─▄▄▀█
██─███─█▄█─███─▄▄▄█─██─█▄▄▄▄─███─████─▄█▀██─▄─▄█
▀▄▄▄▀▄▄▄▀▄▄▄▀▄▄▄▀▀▀▄▄▄▄▀▄▄▄▄▄▀▀▄▄▄▀▀▄▄▄▄▄▀▄▄▀▄▄▀

**Comment by AlexWHite004** [comment]
Since muskets are !!UNRELOADABLE!! (skill issue), I highly recommend not to do that. Plus, as we remember, this will make crossbows non-meta since, AS YOU REMEMBER, the first sturggle comes with getting iron in long-term-sieges, and there's too many zombies. IDEA: Either add penetration to bolts or increase the damage. Or leave it as it is

**Comment by Ctaehko** [comment]
you can reload muskets with musket balls in your inventory with right click :)
iron is easy to get and in abundance unless you have bad eco, iron arrows having penetration would make sense

**Comment by RobotDerevo** [comment]
No need. Closed

**Comment by Gingerbeard5773** [comment]
will not be done as this need is fulfilled by the musket.
