### ISSUE TITLE
migrant coins

### ISSUE THREAD

**Issue by SonantDread** [Gingerbeard5773/Zombies_Reborn#99]
player should get kill credits for migrants in attached vehicles
ie: if player is in a tank and a migrant shoots a zombie to death, the player should get the coin credits

**Comment by TC-DarkSlayer** [comment]
Could make it so that it adds the player's name as this.set_string("employer", playerName);
^ This happens the instance a the player holds migrant and presses "Assign Migrant" to the mounted bow
unassigns whenever he gets off bow, (through unassignment or when bow breaks etc)
Then set damage owner will do the standard player !is null then setdamageowner(player)

**Comment by Gingerbeard5773** [comment]
completed, whoever assigns the migrant to the mounted bow is the damage owner
